# -*- coding: utf-8 -*-
"""9.4.24.hellow world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kKJEPaNCkoZ7opGWDUIa3g5qBRaAXAB
"""

print("hellow world!!")

print("hellow python")

list1=[1,23,3,45,5]

print(list1)

print('My name is Eldmia Ega')

num1=1313
num2=-134
print(num1//num2)

num3=34
num3 +=2
print(num3)

print(pow(3,3))#제곱

print(abs(33))#절대값

print(min(3,4,5,6,6,2,266))#최솟값

print(max(3,4,5,6,8,2,266))#최댓값

print(round(3.14))#반올림

from math import*
print(floor(4.99))#내림
print(ceil(3.14))#올림
print(sqrt(16))#제곱근

from random import*
print(random())#0.0~1.0미만의 임의의 값 생성

from random import*
print(randint(0,10))#0~10미만의 임의의

"""## 사랑해여ㅛ 교수님

"""

import pylab as py

x_deg = py.arange(-180,180+1,)
x_rad = py.deg2rad(x_deg)
y=py.sin(x_rad)

py.plot(x_deg,y)

py.xlabel('x(deg)')
py.ylabel('sin(x)')
py.grid(True)



